# Generated by Django 4.2 on 2024-11-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_usermodel_jwt_auth_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='PluginManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(default=None, max_length=255)),
                ('active', models.BooleanField(default=False)),
                ('identifier', models.CharField(max_length=100, unique=True)),
                ('configuration', models.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='jwt_auth_token',
            field=models.CharField(default='qTn4RIxcE1c33VV', max_length=15),
        ),
    ]
